name: devops
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./application:/var/www/html
    ports:
      - "9003:9003"
    networks:
      - network

  nginx:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./application:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - network

networks:
  network:
    driver: bridge